export type ResponderTeam =
  | 'LANDONLINE - Common Services'
  | 'LANDONLINE - Datacom'
  | 'LANDONLINE - Dealings'
  | 'LANDONLINE - Enablement'
  | 'LANDONLINE - L2 Technical Support'
  | 'LANDONLINE - Legacy Landonline'
  | 'LANDONLINE - Notice of Change'
  | 'LANDONLINE - Search'
  | 'LANDONLINE - Survey External'
  | 'LANDONLINE - Survey Internal'
  | 'LANDONLINE - Titles Internal'
  | 'LINZ - Enterprise Platforms'
  | 'LINZ-BASEMAPS'
  | 'LINZ-BASEMAPS-dev'
  | 'TESTING L2 Escalation'
  | 'TESTING L2 Support';